function[] = generateVTK(ELEM,NODE,PARAMS,disp)
% Bulk Mesh
plotFileBulk = [PARAMS.plotPath PARAMS.plotFileBase '.vtk'];
pFilB = fopen(plotFileBulk,'w','l');

% Header
fprintf(pFilB,'# vtk DataFile Version 2.0\n');
fprintf(pFilB,'Bulk mesh generated by generateVTK.m\n');
fprintf(pFilB,'ASCII\nDATASET UNSTRUCTURED_GRID\n\n');

% Mesh
% Nodal coordinates
fprintf(pFilB,'POINTS %d float\n',length(NODE));
for in=1:length(NODE)
    fprintf(pFilB,'%12.3e%12.3e%12.3e\n',NODE(in).X,NODE(in).Y,0.0);
end

% Connectivity table
plotNod = cell(1,length(ELEM));
for ie=1:length(ELEM)
    pNodCoord = zeros(4,3);
    physicalNodeId = zeros(3,1);
    physNodeCount = 0;
    for in=1:length(ELEM(ie).nodes)
        plotNod{ie} = [plotNod{ie} ELEM(ie).nodes(in)];
        physNodeCount = physNodeCount + 1;
        physicalNodeId(physNodeCount) = length(plotNod{ie});
        pNodCoord(length(plotNod{ie}),1)=NODE(ELEM(ie).nodes(in)).X;
        pNodCoord(length(plotNod{ie}),2)=NODE(ELEM(ie).nodes(in)).Y;
        
    end
end
fprintf(pFilB,'\nCELLS %d %d\n',length(ELEM),length(ELEM)+length(cell2mat(plotNod)));
elmType = zeros(length(ELEM),1);
for ie=1:length(ELEM)
    fprintf(pFilB,'%10d',length(plotNod{ie}));
    for in=1:length(plotNod{ie})
        fprintf(pFilB,'%10d',plotNod{ie}(in)-1);
    end
    fprintf(pFilB,'\n');
    if(length(plotNod{ie})==3)
        elmType(ie)=5;
    elseif(length(plotNod{ie})==4)
        elmType(ie)=9;
    else
        elmType(ie)=7;
    end
end
% Element type
fprintf(pFilB,'\nCELL_TYPES %d\n',length(ELEM));
for ie=1:length(elmType)
    fprintf(pFilB,'%4d\n',elmType(ie));
end
fprintf(pFilB,'\n');

% Point data
fprintf(pFilB,'POINT_DATA %d\n',length(NODE));
fprintf(pFilB,'VECTORS displacement float\n');
for in=1:length(NODE)
    if(PARAMS.ndof==2)
        if(abs(disp(2*in-1))>1e-16 && abs(disp(2*in))>1e-16)
            fprintf(pFilB,'%12.3e%12.3e%12.3e\n',disp(2*in-1),disp(2*in),0.0);
        elseif(abs(disp(2*in-1))>1e-16 && abs(disp(2*in))<1e-16)
            fprintf(pFilB,'%12.3e%12.3e%12.3e\n',disp(2*in-1),0.0,0.0);
        elseif(abs(disp(2*in-1))<1e-16 && abs(disp(2*in))>1e-16)
            fprintf(pFilB,'%12.3e%12.3e%12.3e\n',0.0,disp(2*in),0.0);
        else
            fprintf(pFilB,'%12.3e%12.3e%12.3e\n',0.0,0.0,0.0);
        end
    elseif(PARAMS.ndof==1)
        fprintf(pFilB,'%12.3e%12.3e%12.3e\n',disp(in),0.0,0.0);
    end
end

fclose(pFilB);
